apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-web-hello
  name: go-web-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-hello
  template:
    metadata:
      labels:
        app: go-web-hello
    spec:
      containers:
        - image: grugrut/go-web-hello:latest
          name: go-web-hello
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-web-hello
  name: go-web-hello
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: go-web-hello
