apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: go-web-hello-pipeline-
spec:
  pipelineRef:
    name: go-web-hello-pipeline
  serviceAccountName: build-bot
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: nfs-client
